name: boba-nyc
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - anyio=3.5.0=py310h5588dad_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310he2412df_1
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h0e60522_0
  - boost-cpp=1.74.0=h5b4e17d_5
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h8ffe710_6
  - brotli-bin=1.0.9=h8ffe710_6
  - brotlipy=0.7.0=py310he2412df_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.10.8=h5b45459_0
  - cairo=1.16.0=h15b3021_1009
  - certifi=2021.10.8=py310h5588dad_1
  - cffi=1.15.0=py310hcbf9ad4_0
  - cfitsio=4.0.0=hd67004f_0
  - charset-normalizer=2.0.11=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-completion=0.5.2=py310h5588dad_3
  - click-log=0.3.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.1=py310ha857299_0
  - curl=7.81.0=h789b8ee_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.15.2=py310h5588dad_3
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.4=h39d44d4_0
  - fiona=1.8.20=py310he438f8f_4
  - flit-core=3.6.0=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=h1989441_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py310he2412df_0
  - freetype=2.10.4=h546665d_1
  - freexl=1.0.6=ha8e266a_0
  - gdal=3.4.1=py310h7990aed_2
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geos=3.10.2=h39d44d4_0
  - geotiff=1.7.0=h144821f_6
  - gettext=0.19.8.1=ha2e2712_1008
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.26=pyhd8ed1ab_0
  - greenlet=1.1.2=py310h8a704f9_1
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h2a0e4a3_103
  - icu=69.1=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py310h5588dad_0
  - importlib-resources=3.3.1=pyhd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2022.0.0=h57928b3_3663
  - ipykernel=6.7.0=py310hbbfc1a7_0
  - ipython=7.31.1=py310h5588dad_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py310h5588dad_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-book=0.12.1=pyhd8ed1ab_0
  - jupyter-cache=0.4.3=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.3=pyhd8ed1ab_0
  - jupyter-sphinx=0.3.2=pyhd8ed1ab_1
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py310h5588dad_1
  - jupyter_server=1.13.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - jupytext=1.11.5=pyh6002c4b_0
  - kealib=1.4.14=h8995ca9_3
  - kiwisolver=1.3.2=py310h476a331_1
  - krb5=1.19.2=h20d022d_3
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=13_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_6
  - libbrotlidec=1.0.9=h8ffe710_6
  - libbrotlienc=1.0.9=h8ffe710_6
  - libcblas=3.9.0=13_win64_mkl
  - libcurl=7.81.0=h789b8ee_0
  - libdeflate=1.8=h8ffe710_0
  - libffi=3.4.2=h604cdb4_1
  - libgdal=3.4.1=hb08d4f8_2
  - libglib=2.70.2=h3be07f2_1
  - libiconv=1.16=he774522_0
  - libkml=1.3.0=h9859afa_1014
  - liblapack=3.9.0=13_win64_mkl
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libpng=1.6.37=h1d00b33_2
  - libpq=14.1=hfcc5ef8_1
  - librttopo=1.1.0=hb1df466_9
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=hc2703d3_14
  - libssh2=1.10.0=h680486a_2
  - libtiff=4.3.0=hd413186_2
  - libwebp-base=1.2.2=h8ffe710_1
  - libxml2=2.9.12=hf5bbc77_1
  - libzip=1.8.0=hfed4ece_1
  - libzlib=1.2.11=h8ffe710_1013
  - linkify-it-py=1.0.3=pyhd8ed1ab_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markdown-it-py=1.1.0=pyhd8ed1ab_0
  - markupsafe=2.0.1=py310he2412df_1
  - matplotlib-base=3.5.1=py310h79a7439_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdit-py-plugins=0.2.8=pyhd8ed1ab_0
  - mistune=0.8.4=py310he2412df_1005
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - myst-nb=0.13.1=pyhd8ed1ab_0
  - myst-parser=0.15.2=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py310h5588dad_0
  - nbdime=3.1.1=pyhd8ed1ab_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.8=pyha770c72_0
  - numpy=1.22.1=py310hcae7c84_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.0=py310hf5e1058_0
  - pandoc=2.17.1.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py310h22f3323_0
  - pip=21.2.4=py310haa95532_0
  - pixman=0.40.0=h8ffe710_0
  - poppler=21.11.0=h24fffdf_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.1=h1c22c4f_1
  - proj=8.2.1=h1cfcee9_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.1=py310h5588dad_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pydata-sphinx-theme=0.7.2=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py310h9b3c317_1
  - pyrsistent=0.18.1=py310he2412df_0
  - pysocks=1.7.1=py310h5588dad_4
  - python=3.10.0=h96c0403_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-decouple=3.5=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - pywin32=303=py310he2412df_0
  - pywinpty=2.0.1=py310h00ffb61_0
  - pyyaml=6.0=py310he2412df_3
  - pyzmq=22.3.0=py310h73ada01_1
  - requests=2.27.1=pyhd8ed1ab_0
  - rtree=0.9.7=py310h1cbd46b_3
  - scikit-learn=1.0.2=py310h4dafddf_0
  - scipy=1.7.3=py310h33db832_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py310haa95532_0
  - shapely=1.8.0=py310h3578588_5
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sniffio=1.2.0=py310h5588dad_2
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.4.0=pyh6c4a22f_1
  - sphinx-book-theme=0.1.10=pyhd8ed1ab_0
  - sphinx-comments=0.0.3=pyh9f0ad1d_0
  - sphinx-copybutton=0.4.0=pyhd8ed1ab_0
  - sphinx-external-toc=0.2.3=pyhd8ed1ab_0
  - sphinx-jupyterbook-latex=0.4.6=pyhd8ed1ab_0
  - sphinx-multitoc-numbering=0.1.3=pyhd8ed1ab_0
  - sphinx-panels=0.6.0=pyhd8ed1ab_0
  - sphinx-thebe=0.0.10=pyhd8ed1ab_0
  - sphinx-togglebutton=0.2.3=pyhd3deb0d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=2.2.1=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_1
  - sqlalchemy=1.4.31=py310he2412df_0
  - sqlite=3.37.0=h2bbff1b_0
  - statsmodels=0.13.1=py310h2873277_0
  - tbb=2021.5.0=h2d74725_0
  - terminado=0.13.1=py310h5588dad_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.6.2=h95dad36_0
  - tk=8.6.11=h2bbff1b_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py310he2412df_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py310he2412df_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py310h5588dad_1
  - win_inet_pton=1.1.0=py310h5588dad_3
  - wincertstore=0.2=py310haa95532_2
  - winpty=0.4.3=4
  - xerces-c=3.2.3=h0e60522_4
  - xyzservices=2022.1.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.2=h6255e5f_0
